# Generated by Django 3.2.5 on 2021-08-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsstory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='image_url',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='img_url',
            field=models.URLField(default='https://aeineeuq.github.io/assets/Avatar-hi.png'),
        ),
    ]
